blueprint:
  name: Morning Alarm + TTS Summary
  domain: automation
  author: smarthomeblack
  description: Play alarm sound then speak morning summary

  input:
    notify_time:
      name: Alarm Time
      selector:
        time: {}
      default: "06:15:00"

    calendar_entity:
      name: Calendar
      selector:
        entity:
          multiple: true
          filter:
            - domain: calendar

    calendar_duration:
      name: Calendar Duration
      selector:
        duration:
      default:
        hours: 18

    todo_entity:
      name: Todo
      selector:
        entity:
          multiple: true
          filter:
            - domain: todo
      default: []

    weather_entity:
      name: Weather
      selector:
        entity:
          filter:
            - domain: weather

    custom_footer:
      name: Custom Footer
      selector:
        text:
          multiline: true
      default: ""

    conversation_agent:
      name: Conversation Agent
      selector:
        conversation_agent:

    prompt:
      name: Prompt
      selector:
        text:
          multiline: true
      default: Generate a friendly Vietnamese morning summary.

    speaker:
      name: Speaker
      selector:
        entity:
          domain: media_player

    alarm_file:
      name: Alarm file (in /www/audio/)
      description: "Example: baothuc.mp3"
      default: baothuc.mp3
      selector:
        text: {}

    alarm_volume:
      name: Alarm volume
      default: 0.8
      selector:
        number:
          min: 0
          max: 1
          step: 0.05
          mode: slider

    delay_after_alarm:
      name: Delay after alarm (seconds)
      default: 5
      selector:
        number:
          min: 0
          max: 60
          step: 1

    tts_engine:
      name: TTS Engine
      selector:
        entity:
          domain: tts

    tts_volume:
      name: TTS volume
      default: 0.6
      selector:
        number:
          min: 0
          max: 1
          step: 0.05
          mode: slider

trigger:
  - platform: time
    at: !input notify_time

action:
  - variables:
      speaker: !input speaker
      alarm_file: !input alarm_file
      alarm_volume: !input alarm_volume
      tts_volume: !input tts_volume
      delay_after_alarm: !input delay_after_alarm
      weather_entity: !input weather_entity

  - service: weather.get_forecasts
    data:
      type: hourly
    target:
      entity_id: !input weather_entity
    response_variable: forecast_data

  - variables:
      forecast: "{{ forecast_data[weather_entity].forecast[0] }}"

  - service: calendar.get_events
    data:
      duration: !input calendar_duration
    target:
      entity_id: !input calendar_entity
    response_variable: calendar_response

  - service: todo.get_items
    data:
      status:
        - needs_action
    target:
      entity_id: !input todo_entity
    response_variable: todo_response

  - service: conversation.process
    data:
      agent_id: !input conversation_agent
      text: >
        Time: {{ now().strftime('%A %d/%m %H:%M') }}
        Weather: {{ forecast.condition }} {{ forecast.temperature }}°C
        Calendar: {{ calendar_response }}
        Todo: {{ todo_response }}
        {{ !input prompt }}
    response_variable: agent

  # ===== Play alarm =====
  - service: media_player.volume_set
    target:
      entity_id: !input speaker
    data:
      volume_level: !input alarm_volume

  - service: media_player.play_media
    target:
      entity_id: !input speaker
    data:
      media_content_id: "media-source://media_source/local/{{ alarm_file }}"
      media_content_type: "audio/mpeg"
      metadata:
        title: "{{ alarm_file }}"
        browse_entity_id: !input speaker

  - delay:
      seconds: !input delay_after_alarm

  # ===== Speak summary =====
  - service: media_player.volume_set
    target:
      entity_id: !input speaker
    data:
      volume_level: !input tts_volume

  - service: tts.speak
    target:
      entity_id: !input tts_engine
    data:
      media_player_entity_id: !input speaker
      message: "{{ agent.response.speech.plain.speech }}"

mode: single
