blueprint:
name: Alarm + Repeat Sound + TTS
domain: automation
author: smarthomeblack
description: >
Alarm phát âm từ thư mục www/audio, có lặp lại, chỉnh âm lượng
và đọc TTS sau khi báo thức.

input:
notify_time:
name: Alarm Time
selector:
time: {}
default: "06:15:00"

```
speaker:
  name: Speaker
  selector:
    entity:
      domain: media_player

alarm_sound:
  name: Alarm Sound Path
  description: Ví dụ /local/audio/alarm.mp3
  default: "/local/audio/alarm.mp3"
  selector:
    text: {}

alarm_volume:
  name: Alarm Volume (0.0 - 1.0)
  default: 0.7
  selector:
    number:
      min: 0
      max: 1
      step: 0.05
      mode: slider

repeat_count:
  name: Repeat Times
  default: 3
  selector:
    number:
      min: 1
      max: 20
      step: 1

repeat_delay:
  name: Delay Between Repeats (seconds)
  default: 5
  selector:
    number:
      min: 1
      max: 60
      step: 1

tts_delay:
  name: Delay Before TTS (seconds)
  default: 5
  selector:
    number:
      min: 0
      max: 120
      step: 1

tts_engine:
  name: TTS Engine
  selector:
    entity:
      domain: tts

message:
  name: TTS Message
  default: "Chào buổi sáng. Chúc bạn một ngày tốt lành."
  selector:
    text:
      multiline: true
```

trigger:

* platform: time
  at: !input notify_time

action:

* variables:
  speaker: !input speaker
  alarm_sound: !input alarm_sound
  alarm_volume: !input alarm_volume
  repeat_count: !input repeat_count
  repeat_delay: !input repeat_delay
  tts_delay: !input tts_delay

# Set volume

* service: media_player.volume_set
  target:
  entity_id: !input speaker
  data:
  volume_level: "{{ alarm_volume }}"

# Repeat alarm

* repeat:
  count: "{{ repeat_count }}"
  sequence:
  - service: media_player.play_media
  target:
  entity_id: !input speaker
  data:
  media_content_id: "{{ alarm_sound }}"
  media_content_type: music
  - delay:
  seconds: "{{ repeat_delay }}"

# Delay before TTS

* delay:
  seconds: "{{ tts_delay }}"

# Speak

* service: tts.speak
  target:
  entity_id: !input tts_engine
  data:
  media_player_entity_id: !input speaker
  message: !input message

mode: single
