blueprint:
name: Morning Summary Zalo + Speaker + Alarm
domain: automation
description: Send summary to Zalo and play alarm then TTS on speaker

input:
notify_time:
name: Notification Time
selector:
time: {}

```
zalo_thread_id:
  name: Zalo Thread ID
  selector:
    text: {}

zalo_account_selection:
  name: Zalo Account
  selector:
    text: {}

zalo_type:
  name: Zalo Type
  default: "1"
  selector:
    select:
      options:
        - label: Personal
          value: "0"
        - label: Group
          value: "1"

zalo_ttl:
  name: Zalo TTL
  default: 0
  selector:
    number:
      min: 0
      max: 86400000
      step: 1000

conversation_agent:
  name: Conversation Agent
  selector:
    conversation_agent:

prompt:
  name: Prompt
  default: Tạo thông báo buổi sáng thân thiện bằng tiếng Việt.
  selector:
    text:
      multiline: true

speaker:
  name: Speaker
  default: ""
  selector:
    entity:
      domain: media_player

tts_engine:
  name: TTS Engine
  selector:
    entity:
      domain: tts

enable_chime:
  name: Play alarm before TTS
  default: true
  selector:
    boolean:

chime_file:
  name: Alarm file (www)
  default: /local/alarm.mp3
  selector:
    text:

chime_duration:
  name: Delay before TTS (seconds)
  default: 5
  selector:
    number:
      min: 1
      max: 60
      step: 1
```

trigger:

* platform: time
  at: !input notify_time

action:

* variables:
  speaker: !input speaker
  tts_engine: !input tts_engine
  enable_chime: !input enable_chime
  chime_file: !input chime_file
  chime_duration: !input chime_duration

* service: conversation.process
  data:
  text: !input prompt
  agent_id: !input conversation_agent
  response_variable: agent

* service: zalo_bot.send_message
  data:
  message: "{{ agent.response.speech.plain.speech }}"
  thread_id: !input zalo_thread_id
  account_selection: !input zalo_account_selection
  type: !input zalo_type
  ttl: !input zalo_ttl

* choose:

  * conditions:

    * condition: template
      value_template: "{{ speaker != '' }}"
      sequence:

    * choose:

      * conditions:

        * condition: template
          value_template: "{{ enable_chime }}"
          sequence:

        * service: media_player.play_media
          target:
          entity_id: !input speaker
          data:
          media_content_id: "{{ chime_file }}"
          media_content_type: music

        * delay:
          seconds: !input chime_duration

    * service: tts.speak
      target:
      entity_id: !input tts_engine
      data:
      media_player_entity_id: !input speaker
      message: "{{ agent.response.speech.plain.speech }}"

mode: single
