blueprint:
name: Send summary to Zalo + Speaker (with Alarm)
domain: automation
description: Send morning summary to Zalo and speak on speaker with optional alarm sound before TTS

input:
notify_time:
name: Notification Time
selector:
time: {}

```
zalo_thread_id:
  name: Zalo Thread ID
  selector:
    text: {}

zalo_account_selection:
  name: Zalo Account
  selector:
    text: {}

zalo_type:
  name: Zalo Type
  default: "1"
  selector:
    select:
      options:
        - label: Personal
          value: "0"
        - label: Group
          value: "1"

zalo_ttl:
  name: Zalo TTL
  default: 0
  selector:
    number:
      min: 0
      max: 86400000
      step: 1000

calendar_entity:
  name: Calendar
  selector:
    entity:
      multiple: true
      filter:
        - domain: calendar

calendar_duration:
  name: Calendar Duration
  default:
    hours: 18
  selector:
    duration:

todo_entity:
  name: Todo
  default: []
  selector:
    entity:
      multiple: true
      filter:
        - domain: todo

weather_entity:
  name: Weather
  selector:
    entity:
      filter:
        - domain: weather

custom_footer:
  name: Custom Footer
  default: ""
  selector:
    text:
      multiline: true

conversation_agent:
  name: Conversation Agent
  selector:
    conversation_agent:

prompt:
  name: Prompt
  default: Generate a friendly Vietnamese morning summary.
  selector:
    text:
      multiline: true

# ===== Speaker =====
speaker:
  name: Speaker (optional)
  default: ""
  selector:
    entity:
      domain: media_player

tts_engine:
  name: TTS Engine
  selector:
    entity:
      domain: tts

# ===== Alarm before TTS =====
enable_chime:
  name: Enable alarm sound before TTS
  default: true
  selector:
    boolean:

chime_file:
  name: Chime file (/config/www)
  description: Example: /local/alarm.mp3
  default: /local/alarm.mp3
  selector:
    text:

chime_duration:
  name: Wait time before TTS (seconds)
  default: 3
  selector:
    number:
      min: 1
      max: 60
      step: 1
```

trigger:

* platform: time
  at: !input notify_time

action:

* variables:
  speaker: !input speaker
  tts_engine: !input tts_engine
  enable_chime: !input enable_chime
  chime_file: !input chime_file
  chime_duration: !input chime_duration

# ===== Get AI summary =====

* service: conversation.process
  data:
  text: !input prompt
  agent_id: !input conversation_agent
  response_variable: agent

# ===== Send Zalo =====

* service: zalo_bot.send_message
  data:
  message: "{{ agent.response.speech.plain.speech }}"
  thread_id: !input zalo_thread_id
  account_selection: !input zalo_account_selection
  type: !input zalo_type
  ttl: !input zalo_ttl

# ===== Speaker section =====

* choose:

  * conditions:

    * condition: template
      value_template: "{{ speaker != '' }}"
      sequence:

    # Alarm sound

    * choose:

      * conditions:

        * condition: template
          value_template: "{{ enable_chime }}"
          sequence:
        * service: media_player.play_media
          target:
          entity_id: !input speaker
          data:
          media_content_id: "{{ chime_file }}"
          media_content_type: music
        * delay:
          seconds: !input chime_duration

    # TTS

    * service: tts.speak
      target:
      entity_id: !input tts_engine
      data:
      media_player_entity_id: !input speaker
      message: "{{ agent.response.speech.plain.speech }}"

mode: single
