blueprint:
  name: File Content Analyzer
  author: luuquangvu
  source_url: https://github.com/luuquangvu/tutorials/blob/main/file_content_analyzer_full_llm.yaml
  description: |-
    # Tool designed to analyze and extract all types of information from media and document files

    ## Blueprint Setup

    ### Required

    - An AI Task entity must be created and configured in the System - General settings.

    ### Optional

    - Adjust the prompts for each field used in the script. The descriptions guide the LLM to provide the correct input.

    ### Note

    - Provide a concise and precise description for the script. This description will enable the LLM to recognize that the script is designed to extract data from a media or document file.
    - Make sure to expose the script to Assist after the script has been saved.
    - Do not alter the default script name.
    - Once the script is created, click the three dots in the top right corner, choose "Edit in YAML," and remove the `description: ...` line to restore the default. This step is important because it helps the LLM better understand the script's purpose.
  domain: script
  homeassistant:
    min_version: 2025.8.0
  input:
    ai_task_settings:
      name: Settings for AI Task
      icon: mdi:robot-outline
      description: These settings allow you to set up the AI Task responsible for handling the analyzer task.
      collapsed: true
      input:
        ai_task_entity:
          name: AI Task Entity
          description: If left empty, the system will use the default settings under System - General.
          selector:
            entity:
              filter:
                domain: ai_task
          default:
    prompt_settings:
      name: Prompt settings for the LLM
      icon: mdi:robot
      description: You can use these settings to finetune the prompts for your specific LLM (model). In most cases the defaults should be fine.
      collapsed: true
      input:
        instructions_prompt:
          name: Instructions Prompt
          description: The specific request or query for the AI to analyze the file content
          selector:
            text:
              multiline: true
          default: |-
            Exact data to extract. Returns plain text. Do not invent
        file_path_prompt:
          name: File Path Prompt
          description: The relative file path (local/*) of the document or media to analyze, provided by the AI
          selector:
            text:
              multiline: true
          default: |-
            Relative path (local/*). Precise
        mime_type_prompt:
          name: MIME Type Prompt
          description: The MIME type (e.g., image/jpeg) of the file to analyze, determined by the AI
          selector:
            text:
              multiline: true
          default: |-
            MIME type (e.g. image/jpeg). Must match content
mode: parallel
max_exceeded: silent
description: Analyzes file content (images, video, audio, text) to extract information or provide summaries
variables:
  version: 20260818
fields:
  instructions:
    name: Instructions
    description: !input instructions_prompt
    selector:
      text:
        multiline: true
    required: true
  file_path:
    name: Media Path
    description: !input file_path_prompt
    selector:
      text:
    required: true
  mime_type:
    name: MIME Type
    description: !input mime_type_prompt
    selector:
      text:
    required: true
sequence:
  - variables:
      ai_task_entity: !input ai_task_entity
      instructions: "{{ instructions | default('') | trim }}"
      file_path: "{{ file_path | default('') | trim }}"
      mime_type: "{{ mime_type | default('') | trim | lower }}"
  - if:
      - alias: Check if variables were set correctly
        condition: template
        value_template: "{{ not instructions }}"
    then:
      - alias: Set variable for error message
        variables:
          response:
            error: >-
              Unable to extract data because instructions is missing or incorrect.
      - alias: Stop the script
        stop: >-
          Unable to extract data because instructions is missing or incorrect.
        response_variable: response
  - if:
      - alias: Check if variables were set correctly
        condition: template
        value_template: "{{ (file_path | length == 0) or (not file_path.startswith('local/')) }}"
    then:
      - alias: Set variable for error message
        variables:
          response:
            error: >-
              Unable to extract data because file path is missing or invalid. Specify a path beginning with `local/`, such as `local/folder/file.ext`.
      - alias: Stop the script
        stop: >-
          Unable to extract data because file path is missing or invalid.
        response_variable: response
  - if:
      - alias: Check if variables were set correctly
        condition: template
        value_template: >-
          {{ not (
            mime_type.startswith(('image/', 'video/', 'audio/', 'text/')) or
            mime_type in (
              'application/pdf',
              'application/rtf',
              'application/msword',
              'application/vnd.ms-excel',
              'application/vnd.ms-powerpoint',
              'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
              'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
              'application/vnd.openxmlformats-officedocument.presentationml.presentation'
            )
          ) }}
    then:
      - alias: Set variable for error message
        variables:
          response:
            error: >-
              Unable to extract data because MIME type is missing or incorrect.
      - alias: Stop the script
        stop: >-
          Unable to extract data because MIME type is missing or incorrect.
        response_variable: response
  - variables:
      attachments:
        - media_content_id: media-source://media_source/{{ file_path }}
          media_content_type: "{{ mime_type }}"
  - if:
      - condition: template
        value_template: "{{ not ai_task_entity }}"
    then:
      - action: ai_task.generate_data
        data:
          task_name: Analyze content from a media or document file
          instructions: "{{ instructions }}"
          attachments: "{{ attachments }}"
        response_variable: result
    else:
      - action: ai_task.generate_data
        data:
          task_name: Analyze content from a media or document file
          instructions: "{{ instructions }}"
          attachments: "{{ attachments }}"
          entity_id: "{{ ai_task_entity }}"
        response_variable: result
  - variables:
      response:
        data: "{{ result.data }}"
  - stop: ""
    response_variable: response
