blueprint:
  name: Morning Zalo + Alarm + TTS
  description: Send summary to Zalo, play alarm sound N times, then speak TTS
  domain: automation

  input:
    notify_time:
      name: Notification Time
      default: "06:15:00"
      selector:
        time: {}

    zalo_thread_id:
      name: Zalo Thread ID
      selector:
        text: {}

    zalo_account_selection:
      name: Zalo Account
      selector:
        text: {}

    zalo_type:
      name: Zalo Type
      default: "1"
      selector:
        select:
          options:
            - label: Personal
              value: "0"
            - label: Group
              value: "1"

    zalo_ttl:
      name: Zalo TTL
      default: 0
      selector:
        number:
          min: 0
          max: 86400000
          step: 1000

    weather_entity:
      name: Weather
      selector:
        entity:
          domain: weather

    calendar_entity:
      name: Calendar
      selector:
        entity:
          multiple: true
          domain: calendar

    calendar_duration:
      name: Calendar Duration
      default:
        hours: 18
      selector:
        duration: {}

    todo_entity:
      name: Todo
      default: []
      selector:
        entity:
          multiple: true
          domain: todo

    custom_footer:
      name: Custom Footer
      default: ""
      selector:
        text:
          multiline: true

    conversation_agent:
      name: Conversation Agent
      selector:
        conversation_agent: {}

    prompt:
      name: Prompt
      default: Generate a friendly Vietnamese morning summary.
      selector:
        text:
          multiline: true

    speaker:
      name: Speaker
      default: ""
      selector:
        entity:
          domain: media_player

    tts_engine:
      name: TTS Engine
      selector:
        entity:
          domain: tts

    alarm_sound:
      name: Alarm file (www/audio/)
      default: ""
      selector:
        text: {}

    alarm_repeat:
      name: Alarm repeat times
      default: 1
      selector:
        number:
          min: 1
          max: 10
          step: 1

    alarm_volume:
      name: Alarm volume
      default: 0.8
      selector:
        number:
          min: 0
          max: 1
          step: 0.05

    tts_volume:
      name: TTS volume
      default: 0.6
      selector:
        number:
          min: 0
          max: 1
          step: 0.05

    alarm_delay:
      name: Delay between alarms (seconds)
      default: 3
      selector:
        number:
          min: 0
          max: 60
          step: 1

trigger:
  - platform: time
    at: !input notify_time

mode: single

action:
  - variables:
      speaker: !input speaker
      tts_engine: !input tts_engine
      alarm_sound: !input alarm_sound
      alarm_repeat: !input alarm_repeat
      alarm_volume: !input alarm_volume
      tts_volume: !input tts_volume
      alarm_delay: !input alarm_delay

  - service: zalo_bot.send_message
    data:
      message: "Chào buổi sáng!"
      thread_id: !input zalo_thread_id
      account_selection: !input zalo_account_selection
      type: !input zalo_type
      ttl: !input zalo_ttl

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ speaker != '' }}"
        sequence:

          - service: media_player.volume_set
            target:
              entity_id: !input speaker
            data:
              volume_level: "{{ alarm_volume }}"

          - repeat:
              count: "{{ alarm_repeat }}"
              sequence:
                - condition: template
                  value_template: "{{ alarm_sound != '' }}"

                - service: media_player.play_media
                  target:
                    entity_id: !input speaker
                  data:
                    media_content_id: "/local/audio/{{ alarm_sound }}"
                    media_content_type: music

                - delay:
                    seconds: "{{ alarm_delay }}"

          - service: media_player.volume_set
            target:
              entity_id: !input speaker
            data:
              volume_level: "{{ tts_volume }}"

          - service: tts.speak
            target:
              entity_id: !input tts_engine
            data:
              media_player_entity_id: !input speaker
              message: "Chúc bạn một ngày tốt lành"
