blueprint:
  name: Send summary to Zalo + Speaker
  domain: automation
  author: smarthomeblack
  description: Send morning summary to Zalo and speak on a selected speaker

  input:
    notify_time:
      name: Notification Time
      selector:
        time: {}
      default: "06:15:00"

    zalo_thread_id:
      name: Zalo Thread ID
      selector:
        text: {}

    zalo_account_selection:
      name: Zalo Account
      selector:
        text: {}

    zalo_type:
      name: Zalo Type
      selector:
        select:
          options:
            - label: Personal
              value: "0"
            - label: Group
              value: "1"
      default: "1"

    zalo_ttl:
      name: Zalo TTL
      selector:
        number:
          min: 0
          max: 86400000
          step: 1000
      default: 0

    calendar_entity:
      name: Calendar
      selector:
        entity:
          multiple: true
          filter:
            - domain: calendar

    calendar_duration:
      name: Calendar Duration
      selector:
        duration: {}
      default:
        hours: 18

    todo_entity:
      name: Todo
      selector:
        entity:
          multiple: true
          filter:
            - domain: todo
      default: []

    weather_entity:
      name: Weather
      selector:
        entity:
          filter:
            - domain: weather

    custom_footer:
      name: Custom Footer
      selector:
        text:
          multiline: true
      default: ""

    conversation_agent:
      name: Conversation Agent
      selector:
        conversation_agent: {}

    prompt:
      name: Prompt
      selector:
        text:
          multiline: true
      default: Generate a friendly Vietnamese morning summary.

    speaker:
      name: Speaker (optional)
      default: ""
      selector:
        entity:
          domain: media_player

    tts_engine:
      name: TTS Engine
      selector:
        entity:
          domain: tts

    # ===== Alarm before TTS =====
    alarm_enable:
      name: Enable alarm before TTS
      selector:
        boolean: {}
      default: false

    alarm_sound:
      name: Alarm sound file
      description: "Ví dụ: alarm.mp3 -> /local/audio/alarm.mp3"
      selector:
        text: {}
      default: alarm.mp3

    alarm_delay:
      name: Delay after alarm (seconds)
      selector:
        number:
          min: 0
          max: 30
          step: 1
          unit_of_measurement: seconds
      default: 3

trigger:
  - platform: time
    at: !input notify_time

action:
  - variables:
      weather_entity: !input weather_entity
      calendar_entity: !input calendar_entity
      todo_entity: !input todo_entity
      calendar_duration: !input calendar_duration
      prompt: !input prompt
      custom_footer: !input custom_footer
      speaker: !input speaker
      tts_engine: !input tts_engine
      conversation_agent: !input conversation_agent
      alarm_enable: !input alarm_enable
      alarm_sound: !input alarm_sound
      alarm_delay: !input alarm_delay

  - service: weather.get_forecasts
    data:
      type: hourly
    target:
      entity_id: "{{ weather_entity }}"
    response_variable: forecast_data

  - variables:
      forecast: "{{ forecast_data[weather_entity].forecast[0] }}"

  - service: calendar.get_events
    data:
      duration: !input calendar_duration
    target:
      entity_id: !input calendar_entity
    response_variable: calendar_response

  - service: todo.get_items
    data:
      status:
        - needs_action
    target:
      entity_id: !input todo_entity
    response_variable: todo_response

  - service: conversation.process
    data:
      text: >
        Time: {{ now().strftime('%A %d/%m %H:%M') }}
        Weather: {{ forecast.condition }} {{ forecast.temperature }}
        {{ calendar_response }}
        {{ todo_response }}
        {{ custom_footer }}
        {{ prompt }}
      agent_id: "{{ conversation_agent }}"
    response_variable: agent

  - service: zalo_bot.send_message
    data:
      message: "{{ agent.response.speech.plain.speech }}"
      thread_id: !input zalo_thread_id
      account_selection: !input zalo_account_selection
      type: !input zalo_type
      ttl: !input zalo_ttl

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ speaker != '' }}"
        sequence:

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ alarm_enable }}"
                sequence:
                  - service: media_player.play_media
                    target:
                      entity_id: !input speaker
                    data:
                      media_content_id: "/local/audio/{{ alarm_sound }}"
                      media_content_type: music

                  - delay:
                      seconds: !input alarm_delay

          - service: tts.speak
            target:
              entity_id: !input tts_engine
            data:
              media_player_entity_id: !input speaker
              message: "{{ agent.response.speech.plain.speech }}"

mode: single
