blueprint:
  name: Send summary to Zalo + Speaker (Alarm + Repeat + Volume)
  domain: automation
  author: smarthomeblack
  description: Send morning summary to Zalo and speak on a selected speaker with alarm.

input:
  notify_time:
    name: Notification Time
    selector:
      time: {}
    default: "06:15:00"

  zalo_thread_id:
    name: Zalo Thread ID
    selector:
      text: {}

  zalo_account_selection:
    name: Zalo Account
    selector:
      text: {}

  zalo_type:
    name: Zalo Type
    selector:
      select:
        options:
          - label: Personal
            value: "0"
          - label: Group
            value: "1"
    default: "1"

  zalo_ttl:
    name: Zalo TTL
    selector:
      number:
        min: 0
        max: 86400000
        step: 1000
    default: 0

  calendar_entity:
    name: Calendar
    selector:
      entity:
        multiple: true
        filter:
          - domain: calendar

  calendar_duration:
    name: Calendar Duration
    selector:
      duration: {}
    default:
      hours: 18

  todo_entity:
    name: Todo
    selector:
      entity:
        multiple: true
        filter:
          - domain: todo
    default: []

  weather_entity:
    name: Weather
    selector:
      entity:
        filter:
          - domain: weather

  custom_footer:
    name: Custom Footer
    selector:
      text:
        multiline: true
    default: ""

  conversation_agent:
    name: Conversation Agent
    selector:
      conversation_agent: {}

  prompt:
    name: Prompt
    selector:
      text:
        multiline: true
    default: Generate a friendly Vietnamese morning summary.

  speaker:
    name: Speaker
    selector:
      entity:
        domain: media_player

  tts_engine:
    name: TTS Engine
    selector:
      entity:
        domain: tts

  alarm_enable:
    name: Enable alarm before TTS
    selector:
      boolean: {}
    default: false

  alarm_sound:
    name: Alarm sound filename (www/audio)
    selector:
      text: {}
    default: "baothuc.mp3"

  alarm_repeat:
    name: Alarm repeat count
    selector:
      number:
        min: 1
        max: 10
        step: 1
    default: 1

  alarm_delay:
    name: Delay between alarm repeats (seconds)
    selector:
      number:
        min: 1
        max: 30
        step: 1
    default: 3

  alarm_volume:
    name: Alarm volume
    selector:
      number:
        min: 0
        max: 1
        step: 0.05
    default: 0.7

  tts_volume:
    name: TTS volume
    selector:
      number:
        min: 0
        max: 1
        step: 0.05
    default: 0.5

trigger:
  - platform: time
    at: !input notify_time

action:
  - service: media_player.media_stop
    target:
      entity_id: !input speaker

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ alarm_enable }}"
        sequence:
          - repeat:
              count: !input alarm_repeat
              sequence:
                - service: media_player.volume_set
                  target:
                    entity_id: !input speaker
                  data:
                    volume_level: !input alarm_volume

                - service: media_player.play_media
                  target:
                    entity_id: !input speaker
                  data:
                    media:
                      media_content_id: "media-source://media_source/local/audio/{{ alarm_sound }}"
                      media_content_type: audio/mpeg

                - delay:
                    seconds: !input alarm_delay

                - service: media_player.media_stop
                  target:
                    entity_id: !input speaker

  - service: media_player.volume_set
    target:
      entity_id: !input speaker
    data:
      volume_level: !input tts_volume

  - service: tts.speak
    target:
      entity_id: !input tts_engine
    data:
      media_player_entity_id: !input speaker
      message: "Chào buổi sáng, chúc bạn một ngày tốt lành"

mode: single
