blueprint:
  name: Send summary to Zalo + Speaker (Alarm Extended)
  domain: automation
  author: smarthomeblack + GPT
  description: Send morning summary to Zalo and speak on a selected speaker with alarm options

  input:
    notify_time:
      name: Notification Time
      selector:
        time: {}
      default: "06:15:00"

    # ===== ZALO =====
    enable_zalo:
      name: Enable Send to Zalo
      selector:
        boolean:
      default: true

    zalo_thread_id:
      name: Zalo Thread ID
      selector:
        text: {}

    zalo_account_selection:
      name: Zalo Account
      selector:
        text: {}

    zalo_type:
      name: Zalo Type
      selector:
        select:
          options:
            - label: Personal
              value: "0"
            - label: Group
              value: "1"
      default: "1"

    zalo_ttl:
      name: Zalo TTL
      selector:
        number:
          min: 0
          max: 86400000
          step: 1000
      default: 0

    # ===== DATA =====
    calendar_entity:
      name: Calendar
      selector:
        entity:
          multiple: true
          filter:
            - domain: calendar

    calendar_duration:
      name: Calendar Duration
      selector:
        duration:
      default:
        hours: 18

    todo_entity:
      name: Todo
      selector:
        entity:
          multiple: true
          filter:
            - domain: todo
      default: []

    weather_entity:
      name: Weather
      selector:
        entity:
          filter:
            - domain: weather

    custom_footer:
      name: Custom Footer
      selector:
        text:
          multiline: true
      default: ""

    conversation_agent:
      name: Conversation Agent
      selector:
        conversation_agent:

    prompt:
      name: Prompt
      selector:
        text:
          multiline: true
      default: Generate a friendly Vietnamese morning summary.

    # ===== SPEAKER =====
    speaker:
      name: Speaker
      default: ""
      selector:
        entity:
          domain: media_player

    # ===== ALARM SETTINGS =====
    enable_alarm:
      name: Enable Alarm Sound
      selector:
        boolean:
      default: true

    alarm_url:
      name: Alarm Sound URL
      selector:
        text:
      default: "http://homeassistant.local:8123/local/audio/alarm.mp3"

    alarm_repeat:
      name: Alarm Repeat Times
      selector:
        number:
          min: 1
          max: 10
          step: 1
      default: 2

    alarm_volume:
      name: Alarm Volume (0.0 – 1.0)
      selector:
        number:
          min: 0
          max: 1
          step: 0.05
      default: 0.7

    delay_before_tts:
      name: Delay before TTS (seconds)
      selector:
        number:
          min: 0
          max: 60
          step: 1
      default: 2

    # ===== TTS =====
    enable_tts:
      name: Enable TTS
      selector:
        boolean:
      default: true

    tts_engine:
      name: TTS Engine
      selector:
        entity:
          domain: tts

    tts_volume:
      name: TTS Volume (0.0 – 1.0)
      selector:
        number:
          min: 0
          max: 1
          step: 0.05
      default: 0.6

trigger:
  - platform: time
    at: !input notify_time

action:
  - variables:
      weather_entity: !input weather_entity
      calendar_entity: !input calendar_entity
      todo_entity: !input todo_entity
      calendar_duration: !input calendar_duration
      prompt: !input prompt
      custom_footer: !input custom_footer
      speaker: !input speaker
      enable_zalo: !input enable_zalo
      enable_alarm: !input enable_alarm
      enable_tts: !input enable_tts
      alarm_url: !input alarm_url
      alarm_repeat: !input alarm_repeat
      alarm_volume: !input alarm_volume
      delay_before_tts: !input delay_before_tts
      tts_engine: !input tts_engine
      tts_volume: !input tts_volume

  # ===== WEATHER =====
  - service: weather.get_forecasts
    data:
      type: hourly
    target:
      entity_id: "{{ weather_entity }}"
    response_variable: forecast_data

  - variables:
      forecast: "{{ forecast_data[weather_entity].forecast[0] }}"

  # ===== CALENDAR =====
  - service: calendar.get_events
    data:
      duration: !input calendar_duration
    target:
      entity_id: !input calendar_entity
    response_variable: calendar_response

  # ===== TODO =====
  - service: todo.get_items
    data:
      status:
        - needs_action
    target:
      entity_id: !input todo_entity
    response_variable: todo_response

  # ===== AI SUMMARY =====
  - service: conversation.process
    data:
      text: >
        Time: {{ now().strftime('%A %d/%m %H:%M') }}
        Weather: {{ forecast.condition }} {{ forecast.temperature }}
        {{ calendar_response }}
        {{ todo_response }}
        {{ custom_footer }}
        {{ prompt }}
      agent_id: !input conversation_agent
    response_variable: agent

  # ===== SEND ZALO (OPTIONAL) =====
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ enable_zalo }}"
        sequence:
          - service: zalo_bot.send_message
            data:
              message: "{{ agent.response.speech.plain.speech }}"
              thread_id: !input zalo_thread_id
              account_selection: !input zalo_account_selection
              type: !input zalo_type
              ttl: !input zalo_ttl

  # ===== ALARM SOUND =====
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ enable_alarm and speaker != '' }}"
        sequence:
          - repeat:
              count: "{{ alarm_repeat }}"
              sequence:
                - service: media_player.volume_set
                  target:
                    entity_id: "{{ speaker }}"
                  data:
                    volume_level: "{{ alarm_volume }}"

                - service: media_player.play_media
                  target:
                    entity_id: "{{ speaker }}"
                  data:
                    media_content_id: "{{ alarm_url }}"
                    media_content_type: music

                - delay: "00:00:05"

  # ===== DELAY BEFORE TTS =====
  - delay:
      seconds: "{{ delay_before_tts }}"

  # ===== TTS =====
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ enable_tts and speaker != '' }}"
        sequence:
          - service: media_player.volume_set
            target:
              entity_id: "{{ speaker }}"
            data:
              volume_level: "{{ tts_volume }}"

          - service: tts.speak
            target:
              entity_id: !input tts_engine
            data:
              media_player_entity_id: "{{ speaker }}"
              message: "{{ agent.response.speech.plain.speech }}"

mode: single
